### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by LiMinggang** [itlezy/eMule-build#1]
I used VS 2022 to compile the projects and followed instrunctions in README but still got problems to compile. I tried to build X64.
cximage, libpng and id3lib would fail as below. I think you missed some global variable such as ZLIBSRC for libpng, etc.

  D:\emule\eMule-build\eMule-id3lib-3.9.1\src\io_decorators.cpp(35,10): fatal error C1083: 无法打开包括文件: “zlib.h”: No such
file or directory [D:\emule\eMule-build\eMule-id3lib-3.9.1\libprj\id3lib.vcxproj]

“D:\emule\eMule-build\eMule-CxImage-7.02\CxImage\cximage.vcxproj”(Clean;Build 目标) (1) ->
(ClCompile 目标) ->
  D:\emule\eMule-build\eMule-libpng-1.5.30\png.h(355,13): fatal error C1083: 无法打开包括文件: “pnglibconf.h”: No such file or
directory [D:\emule\eMule-build\eMule-CxImage-7.02\CxImage\cximage.vcxproj]

**Comment by itlezy** [comment]
It is likely this step that is not working for you `002_create_symlinks.cmd`

Can you try running it in a command prompt and check the result?

The result should be a directory named `eMule-zz-deps-links` with symlinks inside, like so

```
 Directory of eMule-build\eMule-zz-deps-links

24/08/2022  11:27    <DIR>          .
24/08/2022  11:27    <DIR>          ..
24/08/2022  11:27    <SYMLINKD>     cryptopp [..\eMule-cryptopp-8.4.0]
24/08/2022  11:27    <SYMLINKD>     CxImage [..\eMule-CxImage-7.02\CxImage]
24/08/2022  11:27    <SYMLINKD>     id3 [..\eMule-id3lib-3.9.1\include\id3]
24/08/2022  11:27    <SYMLINKD>     mbedtls [..\eMule-mbedtls-2.28\include\mbedtls]
24/08/2022  11:27    <SYMLINKD>     miniupnpc [..\eMule-miniupnp-2.2.3\miniupnpc\include]
24/08/2022  11:27    <SYMLINKD>     ResizableLib [..\eMule-ResizableLib\ResizableLib]
24/08/2022  11:27    <SYMLINKD>     zlib [..\eMule-zlib-1.2.12]
```

If the issue persists, bear in mind my installation is VS 2019, whenever I will be able to I will upgrade to VS 2022

**Comment by LiMinggang** [comment]
I had run the file at that time and checked. Everything looks good. I don't know why. I managed to build it successfully though.
![image](https://user-images.githubusercontent.com/4847132/186549017-b4316196-b9f4-41a0-a24b-43dc08c1ce06.png)
